version: "3.8"
services: 
    superhero:
        image: dariomalchiodi/sad
        ports: 
            - "8888:8888"
        volumes: 
            - ./:/home/jovyan/my-work dariomalchiodi/sad
        tty: true
        stdin_open: true